export const FAILURE = 'FAILURE';
export const SUCCESS = 'SUCCESS';

export const GET_TOUR = 'GET_TOUR';
export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS';

export const ADD_TOUR = 'ADD_TOUR';
export const ADD_TOUR_SUCCESS = 'ADD_TOUR_SUCCESS';

export const EDIT_TOUR = 'EDIT_TOUR';
export const UPDATE_TOUR = 'UPDATE_TOUR';
export const UPDATE_TOUR_SUCCESS = 'UPDATE_TOUR_SUCCESS';

export const DELETE_TOUR = 'DELETE_TOUR';
export const DELETE_TOUR_SUCCESS = 'DELETE_TOUR_SUCCESS';

export const GET_TOUR_DETAIL = 'GET_TOUR_DETAIL';
export const GET_TOUR_DETAIL_SUCCESS = 'GET_TOUR_DETAIL_SUCCESS';

export const ADD_TOUR_DETAIL = 'ADD_TOUR_DETAIL';
export const ADD_TOUR_DETAIL_SUCCESS = 'ADD_TOUR_DETAIL_SUCCESS';

export const EDIT_TOUR_DETAIL = 'EDIT_TOUR_DETAIL';
export const UPDATE_TOUR_DETAIL = 'UPDATE_TOUR_DETAIL';
export const UPDATE_TOUR_DETAIL_SUCCESS = 'UPDATE_TOUR_DETAIL_SUCCESS';

export const DELETE_TOUR_DETAIL = 'DELETE_TOUR_DETAIL';
export const DELETE_TOUR_DETAIL_SUCCESS = 'DELETE_TOUR_DETAIL_SUCCESS';

export const TOGGLE_TOUR_MODAL = 'TOGGLE_TOUR_MODAL';

export const TOGGLE_TOUR_DETAIL_MODAL = 'TOGGLE_TOUR_DETAIL_MODAL';

export const TOGGLE_LOADER = 'TOGGLE_LOADER';
